// Imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/Header'

// Styles
import './globals.css'

// Fonts
const inter = Inter({ subsets: ['latin'] })

// SEO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="bg-secondary px-[5%]">{children}</div>
      </body>
    </html>
  )
}
